name: push_notification_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  equatable: ^2.0.5
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.19
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_local_notifications: ^17.0.0
  go_router: ^13.2.1

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
